### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by helloitsjoe** [helloitsjoe/jot#1]
## Description

Working MVP

## TODO

- [x] "Submit" page
  - [x] Form
  - [x] Tags
    - [x] Dropdown uses fetched tags
  - [x] Recent tags fetch and auto-populate
  - [x] Clicking tag adds to form
  - [x] Input for new tags
  - [x] Creating a new tag makes it available to other notes
- [x] "View" page
  - [x] View notes grouped by most recent tag
  - [x] Clicking multiple tags narrows search
